name: build toolchain

on:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai 

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write

    steps:
      - name: set timezone
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          date +"%Y-%m-%d %H:%M:%S %Z"

      - name: system info
        run: |
          date +"%Y-%m-%d %H:%M:%S %Z"
          lscpu | grep -E '^Architecture|^CPU\(s\):|^Model name'
          uname -sr
          lsb_release -a
          free -h
          df -Th

      - name: checkout
        uses: actions/checkout@v4

      - name: build
        uses: apoiston/actions@toolchain
        with:
          config_buildinfo: builder/config.buildinfo
          private_key: ${{ secrets.PRIVATE_KEY }}
          public_key: ${{ secrets.PUBLIC_KEY }}
          prepare_compile: ${{ secrets.PREPARE_COMPILE }}
          prepare_configure: ${{ secrets.PREPARE_CONFIGURE }}
          prepare_toolchain: ${{ secrets.PREPARE_TOOLCHAIN }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: toolchain
          path: |
            openwrt/builder/*.zst
            openwrt/builder/*.txt
